### ISSUE TITLE
argument type verification on function registration missing

### ISSUE THREAD

**Issue by mkind** [splone/splonebox-core#13]
We should verify, that the argument to associate with a function during registration is of valid type.

**Comment by stze** [comment]
Since every msgpack-rpc message is deserialized in _unpack.c_, a message_object can not hold an unknown type value. This is because if an invalid msgpack-rpc type is detected the deserialization process is interrupted and no `message_object` is generated. If the msgpack-rpc type is valid, the type gets translated to a value of `message_object_type`.
